version: '3.2'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: 1000:1000
    ports:
    - 3000:3000
    #environment:
    #- GF_INSTALL_PLUGINS=camptocamp-prometheus-alertmanager-datasource,simpod-json-datasource
    volumes:
    - ./grafana_data:/var/lib/grafana
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/var/lib/prometheus/prometheus
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - ./prometheus_data:/var/lib/prometheus/prometheus
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - portal
  portal:
    container_name: portal
    build:
      context: ./portal-container
      args:
        JOBS: 3
        USE_NICE: 1
    cap_add:
      - SYS_NICE
  stress-container:
    container_name: stress-container
    build:
      context: ./stress-container
      args:
        CPUS: 14
    cap_add:
      - SYS_NICE
    depends_on:
    - portal
